# Generated by Django 4.0.5 on 2023-01-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_dir', models.CharField(max_length=5, null=True)),
                ('wind_angle', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('solar_rad', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('uv_dose', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_val', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
