# Generated by Django 4.1.5 on 2023-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='leaf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
